// This is an autogenerated file. DO NOT edit.
'use server';
/**
 * @fileOverview This file contains the Genkit flow for FODMAP detection in food items.
 *
 * - analyzeFoodItem - Analyzes a food item and calculates a FODMAP score for each ingredient.
 * - AnalyzeFoodItemInput - The input type for the analyzeFoodItem function.
 * - AnalyzeFoodItemOutput - The return type for the analyzeFoodItem function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeFoodItemInputSchema = z.object({
  foodItem: z.string().describe('The name of the food item to analyze.'),
  ingredients: z.string().describe('A comma-separated list of ingredients in the food item.'),
});
export type AnalyzeFoodItemInput = z.infer<typeof AnalyzeFoodItemInputSchema>;

const FodmapScoreSchema = z.enum(['Green', 'Yellow', 'Red']);

const AnalyzeFoodItemOutputSchema = z.object({
  ingredientFodmapScores: z.record(FodmapScoreSchema).describe('A map of ingredients to their FODMAP scores (Green, Yellow, or Red).'),
  overallRisk: FodmapScoreSchema.describe('The overall FODMAP risk level of the food item (Green, Yellow, or Red).'),
  reason: z.string().describe('Explanation of why food item has the assigned risk level.'),
});
export type AnalyzeFoodItemOutput = z.infer<typeof AnalyzeFoodItemOutputSchema>;

export async function analyzeFoodItem(input: AnalyzeFoodItemInput): Promise<AnalyzeFoodItemOutput> {
  return analyzeFoodItemFlow(input);
}

const analyzeFoodItemPrompt = ai.definePrompt({
  name: 'analyzeFoodItemPrompt',
  input: {schema: AnalyzeFoodItemInputSchema},
  output: {schema: AnalyzeFoodItemOutputSchema},
  prompt: `You are an AI assistant specialized in FODMAP analysis of food items. 
FODMAPs are types of carbohydrates that can cause digestive issues for people with Irritable Bowel Syndrome (IBS). 
You will receive a food item and a list of its ingredients. Your task is to analyze each ingredient and determine its FODMAP score (Green, Yellow, or Red) based on common FODMAP content. 

Here's a guide for FODMAP scoring:

*   Green: Low FODMAP content. Generally safe for people with IBS.
*   Yellow: Moderate FODMAP content. May cause issues for some people with IBS.
*   Red: High FODMAP content. Likely to cause issues for people with IBS.

Consider common FODMAPs such as Fructose, Lactose, Fructans, Galactans, and Polyols when analyzing ingredients.

Food Item: {{{foodItem}}}
Ingredients: {{{ingredients}}}

Output a JSON object with the ingredientFodmapScores for each ingredient, the overallRisk for the food item, and the reason for the risk level assignment.
`,
});

const analyzeFoodItemFlow = ai.defineFlow(
  {
    name: 'analyzeFoodItemFlow',
    inputSchema: AnalyzeFoodItemInputSchema,
    outputSchema: AnalyzeFoodItemOutputSchema,
  },
  async input => {
    const {output} = await analyzeFoodItemPrompt(input);
    return output!;
  }
);
